spring.application.name=Academia

# Configuracao do banco em memoria H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilita o console web para visualizar o banco no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostra os comandos SQL no terminal e atualiza as tabelas automaticamente
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update